import pygame


FRAME_RATE = 60
ANIM_FRAME_RATE = 60
GAME_SIZE = (800, 480)
SCREEN_SIZE = (800, 480)
FONT_ANTIALIAS = True
SDL_FLAGS = 0
GCW_ZERO = False
if GCW_ZERO:
    FRAME_RATE = 60
    GAME_SIZE = (640, 480)
    SCREEN_SIZE = (320, 240)
    FONT_ANTIALIAS = False
    SDL_FLAGS = pygame.FULLSCREEN
DEFLECTION_AUTOAIM_ANGLE = 45
DEFLECTION_SPEED_SCALE = 3
ENEMY_TARGET_OFFSET = 64
FLOOR_Y = int(GAME_SIZE[1] * 0.75)
DEBUG_DRAW_SPRITE_BOUNDS = False
DEBUG_DRAW_SPRITE_ANCHOR = False
DEBUG_DRAW_SPRITE_BODY = False
DEBUG_SHOW_FPS = False