SHOW_HIT_ZONES = False
SCREEN_SIZE = (800, 600)
DEFLECTION_AUTOAIM_ANGLE = 90
DEFLECTION_SPEED_SCALE = 1.5
FLOOR_Y = 459
DEBUG_DRAW_SPRITE_BOUNDS = False
DEBUG_DRAW_SPRITE_ANCHOR = False
DEBUG_DRAW_SPRITE_BODY = False